os: linux
language: python
sudo: required
services:
  - docker
env:
  global:
    - CONAN_UPLOAD: 1
    - CONAN_REFERENCE: "ZMQ/4.1.1"
    - CONAN_USERNAME: "memsharded"
    - CONAN_CHANNEL: "testing"
    - CONAN_TOTAL_PAGES: 1
  matrix:
    - CONAN_GCC_VERSIONS: 4.8 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS: 4.9 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS: 5.2 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS: 5.3 CONAN_USE_DOCKER=1

matrix:
   include:
       - os: osx 
         osx_image: xcode7.3 # apple-clang 7.3
         language: generic
         env: CONAN_CURRENT_PAGE=1   
       - os: osx 
         osx_image: xcode7.1 # apple-clang 7.0
         language: generic
         env: CONAN_CURRENT_PAGE=1   
       - os: osx
         osx_image: xcode6.4 # apple-clang 6.1
         language: generic
         env: CONAN_CURRENT_PAGE=1      
       - os: osx 
         osx_image: xcode6.2 # apple-clang 6.0
         language: generic
         env: CONAN_CURRENT_PAGE=1

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
