env:
  global:
    - CONAN_DOCKER_32_IMAGES: 1

linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.6"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:
      - <<: *linux
        env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Debug
      - <<: *linux
        env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Release
      - <<: *linux
        env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Debug
      - <<: *linux
        env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release
      - <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc5 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc5 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc5 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc5 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc5 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc5 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc5 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc5 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc6 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc6 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc6 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc6 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc6 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc6 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc6 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc6 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=lasote/conangcc8 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=lasote/conangcc8 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=lasote/conangcc8 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=lasote/conangcc8 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=lasote/conangcc8 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=lasote/conangcc8 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=lasote/conangcc8 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=lasote/conangcc8 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=3 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=4 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=3 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=4 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=3 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=4 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=3 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=4 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=3 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=4 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=3 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=4 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=3 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=4 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=3 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=4 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=5.0 CONAN_DOCKER_IMAGE=lasote/conanclang50 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=5.0 CONAN_DOCKER_IMAGE=lasote/conanclang50 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=5.0 CONAN_DOCKER_IMAGE=lasote/conanclang50 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=3 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=5.0 CONAN_DOCKER_IMAGE=lasote/conanclang50 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=4 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=5.0 CONAN_DOCKER_IMAGE=lasote/conanclang50 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=5.0 CONAN_DOCKER_IMAGE=lasote/conanclang50 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=5.0 CONAN_DOCKER_IMAGE=lasote/conanclang50 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=3 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=5.0 CONAN_DOCKER_IMAGE=lasote/conanclang50 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=4 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=5.0 CONAN_DOCKER_IMAGE=lasote/conanclang50 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=5.0 CONAN_DOCKER_IMAGE=lasote/conanclang50 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=5.0 CONAN_DOCKER_IMAGE=lasote/conanclang50 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=3 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=5.0 CONAN_DOCKER_IMAGE=lasote/conanclang50 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=4 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=5.0 CONAN_DOCKER_IMAGE=lasote/conanclang50 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=5.0 CONAN_DOCKER_IMAGE=lasote/conanclang50 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=5.0 CONAN_DOCKER_IMAGE=lasote/conanclang50 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=3 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=5.0 CONAN_DOCKER_IMAGE=lasote/conanclang50 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=4 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=lasote/conanclang60 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=lasote/conanclang60 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=lasote/conanclang60 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=3 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=lasote/conanclang60 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=4 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=lasote/conanclang60 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=lasote/conanclang60 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=lasote/conanclang60 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=3 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=lasote/conanclang60 CONAN_ARCHS=x86 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=4 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=lasote/conanclang60 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=lasote/conanclang60 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=lasote/conanclang60 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=3 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=lasote/conanclang60 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Debug CONAN_CURRENT_PAGE=4 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=lasote/conanclang60 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=lasote/conanclang60 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=lasote/conanclang60 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=3 CONAN_TOTAL_PAGES=4
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=lasote/conanclang60 CONAN_ARCHS=x86_64 CONAN_BUILD_TYPES=Release CONAN_CURRENT_PAGE=4 CONAN_TOTAL_PAGES=4
      - <<: *osx
        osx_image: xcode7.3
        env: CONAN_APPLE_CLANG_VERSIONS=7.3 CONAN_BUILD_TYPES=Debug
      - <<: *osx
        osx_image: xcode7.3
        env: CONAN_APPLE_CLANG_VERSIONS=7.3 CONAN_BUILD_TYPES=Release
      - <<: *osx
        osx_image: xcode8.3
        env: CONAN_APPLE_CLANG_VERSIONS=8.1 CONAN_BUILD_TYPES=Debug
      - <<: *osx
        osx_image: xcode8.3
        env: CONAN_APPLE_CLANG_VERSIONS=8.1 CONAN_BUILD_TYPES=Release
      - <<: *osx
        osx_image: xcode9
        env: CONAN_APPLE_CLANG_VERSIONS=9.0 CONAN_BUILD_TYPES=Debug
      - <<: *osx
        osx_image: xcode9
        env: CONAN_APPLE_CLANG_VERSIONS=9.0 CONAN_BUILD_TYPES=Release
      - <<: *osx
        osx_image: xcode9.3
        env: CONAN_APPLE_CLANG_VERSIONS=9.1 CONAN_BUILD_TYPES=Debug
      - <<: *osx
        osx_image: xcode9.3
        env: CONAN_APPLE_CLANG_VERSIONS=9.1 CONAN_BUILD_TYPES=Release

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
