build: false

environment:
    PYTHON: "C:\\Python37"

    matrix:
        #- MINGW_CONFIGURATIONS: '4.9@x86_64@seh@posix, 4.9@x86_64@sjlj@posix, 4.9@x86@sjlj@posix, 4.9@x86@dwarf2@posix, 6@x86_64@seh@posix, 7@x86_64@seh@posix'
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_BUILD_TYPES: Release
          CONAN_ARCHS: x86
          CONAN_VISUAL_RUNTIMES: MT
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_BUILD_TYPES: Release
          CONAN_ARCHS: x86
          CONAN_VISUAL_RUNTIMES: MD
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_BUILD_TYPES: Release
          CONAN_ARCHS: x86_64
          CONAN_VISUAL_RUNTIMES: MT
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_BUILD_TYPES: Release
          CONAN_ARCHS: x86_64
          CONAN_VISUAL_RUNTIMES: MD
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_BUILD_TYPES: Debug
          CONAN_ARCHS: x86
          CONAN_VISUAL_RUNTIMES: MTd
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_BUILD_TYPES: Debug
          CONAN_ARCHS: x86
          CONAN_VISUAL_RUNTIMES: MDd
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_BUILD_TYPES: Debug
          CONAN_ARCHS: x86_64
          CONAN_VISUAL_RUNTIMES: MTd
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_BUILD_TYPES: Debug
          CONAN_ARCHS: x86_64
          CONAN_VISUAL_RUNTIMES: MDd
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Release
          CONAN_ARCHS: x86
          CONAN_VISUAL_RUNTIMES: MT
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Release
          CONAN_ARCHS: x86
          CONAN_VISUAL_RUNTIMES: MD
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Release
          CONAN_ARCHS: x86_64
          CONAN_VISUAL_RUNTIMES: MT
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Release
          CONAN_ARCHS: x86_64
          CONAN_VISUAL_RUNTIMES: MD
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Debug
          CONAN_ARCHS: x86
          CONAN_VISUAL_RUNTIMES: MTd
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Debug
          CONAN_ARCHS: x86
          CONAN_VISUAL_RUNTIMES: MDd
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Debug
          CONAN_ARCHS: x86_64
          CONAN_VISUAL_RUNTIMES: MTd
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Debug
          CONAN_ARCHS: x86_64
          CONAN_VISUAL_RUNTIMES: MDd

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools bincrafters_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py
